addSbtPlugin("io.get-coursier"  % "sbt-coursier"          % "1.0.0-RC13")
addSbtPlugin("com.lucidchart"   % "sbt-scalafmt-coursier" % "1.15")
addSbtPlugin("org.lyranthe.sbt" % "partial-unification"   % "1.1.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"           % "0.3.4")
addSbtPlugin("ch.epfl.scala"    % "sbt-bloop"             % "1.0.0-M9")

addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "0.4.0")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "0.4.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "0.6.22")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"              % "0.3.7")
